# Generated by Django 3.0 on 2021-10-19 10:30

from django.db import migrations, models
import django_fsm


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('product', models.CharField(max_length=128)),
                ('status', django_fsm.FSMIntegerField(choices=[(0, 'created'), (1, 'paid'), (2, 'fullfilled'), (3, 'cancelled'), (4, 'returned')], default=0, protected=True)),
            ],
        ),
    ]
